// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using psH60A01.Models;

#nullable disable

namespace psH60A01.Migrations
{
    [DbContext(typeof(H60AssignmentDbPsContext))]
    partial class H60AssignmentDbPsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("psH60A01.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingCartCartId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartCartId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            Price = 10.99m,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 1,
                            Price = 5.99m,
                            ProductId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("psH60A01.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreditCard = "1234567890123456",
                            Email = "paula@example.com",
                            FirstName = "Paula",
                            LastName = "Selskiy",
                            PhoneNumber = "8195551234",
                            Province = "QC"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreditCard = "2345678901234567",
                            Email = "stella@example.com",
                            FirstName = "Stella",
                            LastName = "Hatton",
                            PhoneNumber = "8195555678",
                            Province = "ON"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreditCard = "3456789012345678",
                            Email = "chaicat@example.com",
                            FirstName = "Chai",
                            LastName = "Hatton",
                            PhoneNumber = "8195559012",
                            Province = "QC"
                        });
                });

            modelBuilder.Entity("psH60A01.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFulfilled")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Taxes")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFulfilled = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Taxes = 1.60m,
                            Total = 15.97m
                        });
                });

            modelBuilder.Entity("psH60A01.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            Price = 5.99m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            Price = 3.99m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 1,
                            Price = 4.99m,
                            ProductId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("psH60A01.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal?>("BuyPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProdCatId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "ProdCatId" }, "IX_Product_ProdCatId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BuyPrice = 4.50m,
                            Description = "Wooden hook",
                            Manufacturer = "Red Heart",
                            ProdCatId = 1,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 2,
                            BuyPrice = 2.50m,
                            Description = "Plastic hook",
                            Manufacturer = "Red Heart",
                            ProdCatId = 1,
                            SellPrice = 3.99m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 3,
                            BuyPrice = 3.60m,
                            Description = "Metal hook",
                            Manufacturer = "Lion Brand",
                            ProdCatId = 1,
                            SellPrice = 4.99m,
                            Stock = 36
                        },
                        new
                        {
                            ProductId = 4,
                            BuyPrice = 6.50m,
                            Description = "Ergonomic hook",
                            Manufacturer = "Clover Armour",
                            ProdCatId = 1,
                            SellPrice = 10.99m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 5,
                            BuyPrice = 4.50m,
                            Description = "Wooden needles",
                            Manufacturer = "Red Heart",
                            ProdCatId = 2,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 6,
                            BuyPrice = 4.50m,
                            Description = "Plastic needles",
                            Manufacturer = "Red Heart",
                            ProdCatId = 2,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 7,
                            BuyPrice = 4.50m,
                            Description = "Metal needles",
                            Manufacturer = "Red Heart",
                            ProdCatId = 2,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 8,
                            BuyPrice = 4.50m,
                            Description = "Circular needles",
                            Manufacturer = "Red Heart",
                            ProdCatId = 2,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 9,
                            BuyPrice = 4.50m,
                            Description = "Merino wool",
                            Manufacturer = "Red Heart",
                            ProdCatId = 3,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 10,
                            BuyPrice = 4.50m,
                            Description = "Cotton yarn",
                            Manufacturer = "Red Heart",
                            ProdCatId = 3,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 11,
                            BuyPrice = 4.50m,
                            Description = "Alpacca wool",
                            Manufacturer = "Red Heart",
                            ProdCatId = 3,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 12,
                            BuyPrice = 4.50m,
                            Description = "Silk yarn",
                            Manufacturer = "Red Heart",
                            ProdCatId = 3,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 13,
                            BuyPrice = 4.50m,
                            Description = "Knit socks",
                            Manufacturer = "Red Heart",
                            ProdCatId = 4,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 14,
                            BuyPrice = 4.50m,
                            Description = "Cat amigurumi",
                            Manufacturer = "Red Heart",
                            ProdCatId = 4,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 15,
                            BuyPrice = 4.50m,
                            Description = "Crochet blanket",
                            Manufacturer = "Red Heart",
                            ProdCatId = 4,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 16,
                            BuyPrice = 4.50m,
                            Description = "Cozy sweather",
                            Manufacturer = "Red Heart",
                            ProdCatId = 4,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 17,
                            BuyPrice = 4.50m,
                            Description = "Felting needle",
                            Manufacturer = "Red Heart",
                            ProdCatId = 5,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 18,
                            BuyPrice = 4.50m,
                            Description = "Felting mat",
                            Manufacturer = "Red Heart",
                            ProdCatId = 5,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 19,
                            BuyPrice = 4.50m,
                            Description = "Needle handle",
                            Manufacturer = "Red Heart",
                            ProdCatId = 5,
                            SellPrice = 5.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 20,
                            BuyPrice = 4.50m,
                            Description = "Finger guards",
                            Manufacturer = "Red Heart",
                            ProdCatId = 5,
                            SellPrice = 5.99m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("psH60A01.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ProdCat")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProdCat = "Crochet hooks"
                        },
                        new
                        {
                            CategoryId = 2,
                            ProdCat = "Knitting needles"
                        },
                        new
                        {
                            CategoryId = 3,
                            ProdCat = "Yarn"
                        },
                        new
                        {
                            CategoryId = 4,
                            ProdCat = "Patterns"
                        },
                        new
                        {
                            CategoryId = 5,
                            ProdCat = "Felting tools"
                        });
                });

            modelBuilder.Entity("psH60A01.Models.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CustomerId = 2,
                            DateCreated = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("psH60A01.Models.CartItem", b =>
                {
                    b.HasOne("psH60A01.Models.ShoppingCart", "ShoppingCart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("psH60A01.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("psH60A01.Models.ShoppingCart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartCartId");

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("psH60A01.Models.Order", b =>
                {
                    b.HasOne("psH60A01.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("psH60A01.Models.OrderItem", b =>
                {
                    b.HasOne("psH60A01.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("psH60A01.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("psH60A01.Models.Product", b =>
                {
                    b.HasOne("psH60A01.Models.ProductCategory", "ProdCat")
                        .WithMany("Products")
                        .HasForeignKey("ProdCatId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProdCat");
                });

            modelBuilder.Entity("psH60A01.Models.ShoppingCart", b =>
                {
                    b.HasOne("psH60A01.Models.Customer", "Customer")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("psH60A01.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("psH60A01.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("psH60A01.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("psH60A01.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("psH60A01.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
